### ISSUE TITLE
getting error on running

### ISSUE THREAD

**Issue by amansaxena1** [masud70/qCompiler#2]
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

AssertionError [ERR_ASSERTION]: Unsupported platform.

**Comment by masud70** [comment]
The given information shows that you are trying to use the package on a platform that is not supported.

If further assistance is required, please provide details so that we can help resolve the issue.

**Comment by amansaxena1** [comment]
got it, thanks [masud70](https://github.com/masud70)
